#!/usr/bin/env node

/**
 * Quick Setup Script for Trading Application
 * This script helps you set up the trading application quickly
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function question(query) {
    return new Promise(resolve => rl.question(query, resolve));
}

async function setupEnvironment() {
    console.log('🚀 Trading Application Setup\n');
    console.log('This script will help you configure your environment variables.\n');

    // Read current .env file
    const envPath = path.join(__dirname, '../.env');
    let envContent = '';
    
    try {
        envContent = fs.readFileSync(envPath, 'utf8');
    } catch (error) {
        console.log('⚠️  .env file not found, creating a new one...');
    }

    console.log('📝 Please provide the following information:\n');

    // Collect configuration
    const config = {};
    
    // Database Configuration
    console.log('📊 Database Configuration:');
    config.MONGODB_URI = await question('MongoDB URI (default: mongodb://localhost:27017/trading-app): ');
    if (!config.MONGODB_URI.trim()) {
        config.MONGODB_URI = 'mongodb://localhost:27017/trading-app';
    }

    // JWT Configuration
    console.log('\n🔐 Security Configuration:');
    config.JWT_SECRET = await question('JWT Secret (leave empty to generate): ');
    if (!config.JWT_SECRET.trim()) {
        config.JWT_SECRET = require('crypto').randomBytes(64).toString('hex');
        console.log('✅ Generated JWT secret');
    }

    config.SESSION_SECRET = await question('Session Secret (leave empty to generate): ');
    if (!config.SESSION_SECRET.trim()) {
        config.SESSION_SECRET = require('crypto').randomBytes(64).toString('hex');
        console.log('✅ Generated session secret');
    }

    // Zerodha Configuration
    console.log('\n📈 Zerodha Kite Connect API:');
    config.KITE_API_KEY = await question('Kite API Key: ');
    config.KITE_API_SECRET = await question('Kite API Secret: ');
    
    // Google OAuth (optional)
    console.log('\n🔍 Google OAuth (Optional - press Enter to skip):');
    config.GOOGLE_CLIENT_ID = await question('Google Client ID: ');
    config.GOOGLE_CLIENT_SECRET = await question('Google Client Secret: ');

    // Server Configuration
    console.log('\n⚙️  Server Configuration:');
    config.PORT = await question('Server Port (default: 3000): ');
    if (!config.PORT.trim()) {
        config.PORT = '3000';
    }

    config.NODE_ENV = await question('Environment (development/production, default: development): ');
    if (!config.NODE_ENV.trim()) {
        config.NODE_ENV = 'development';
    }

    // Generate .env content
    const envVariables = {
        // Server Configuration
        PORT: config.PORT,
        NODE_ENV: config.NODE_ENV,
        
        // Database Configuration
        MONGODB_URI: config.MONGODB_URI,
        
        // JWT Configuration
        JWT_SECRET: config.JWT_SECRET,
        
        // Session Configuration
        SESSION_SECRET: config.SESSION_SECRET,
        
        // Zerodha Kite Connect API Configuration
        KITE_API_KEY: config.KITE_API_KEY,
        KITE_API_SECRET: config.KITE_API_SECRET,
        KITE_REDIRECT_URL: `http://localhost:${config.PORT}/api/auth/broker/zerodha/callback`,
        
        // Google OAuth Configuration
        GOOGLE_CLIENT_ID: config.GOOGLE_CLIENT_ID || 'enter your google client id',
        GOOGLE_CLIENT_SECRET: config.GOOGLE_CLIENT_SECRET || 'enter your google client secret',
        GOOGLE_REDIRECT_URL: `http://localhost:${config.PORT}/api/auth/google/callback`,
        
        // WebSocket Configuration
        WS_HOST: 'ws.kite.trade',
        WS_PORT: '443'
    };

    // Create .env file content
    let newEnvContent = '# Trading Application Environment Configuration\n';
    newEnvContent += '# Generated by setup script\n\n';

    // Group variables by category
    const categories = {
        'Server Configuration': ['PORT', 'NODE_ENV'],
        'Database Configuration': ['MONGODB_URI'],
        'JWT Configuration': ['JWT_SECRET'],
        'Session Configuration': ['SESSION_SECRET'],
        'Zerodha Kite Connect API Configuration': ['KITE_API_KEY', 'KITE_API_SECRET', 'KITE_REDIRECT_URL'],
        'Google OAuth Configuration': ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_REDIRECT_URL'],
        'WebSocket Configuration': ['WS_HOST', 'WS_PORT']
    };

    Object.entries(categories).forEach(([category, vars]) => {
        newEnvContent += `# ${category}\n`;
        vars.forEach(varName => {
            newEnvContent += `${varName}=${envVariables[varName]}\n`;
        });
        newEnvContent += '\n';
    });

    // Write .env file
    fs.writeFileSync(envPath, newEnvContent);
    console.log('\n✅ .env file created successfully!\n');

    // Display summary
    console.log('📋 Configuration Summary:');
    console.log('========================');
    console.log(`Database: ${config.MONGODB_URI}`);
    console.log(`Server Port: ${config.PORT}`);
    console.log(`Environment: ${config.NODE_ENV}`);
    console.log(`Kite API Key: ${config.KITE_API_KEY ? '✅ Configured' : '❌ Not configured'}`);
    console.log(`Google OAuth: ${config.GOOGLE_CLIENT_ID ? '✅ Configured' : '⚠️  Skipped (optional)'}`);

    console.log('\n🚀 Next Steps:');
    console.log('==============');
    console.log('1. Install dependencies: npm install');
    console.log('2. Start MongoDB if running locally');
    console.log('3. Start the application: npm run dev');
    console.log('4. Visit http://localhost:' + config.PORT + '/api for API documentation');
    console.log('5. Use examples/api-usage-examples.js to test the API');

    if (!config.KITE_API_KEY) {
        console.log('\n⚠️  Warning: Kite API credentials not configured');
        console.log('   - Get your API credentials from https://kite.trade/');
        console.log('   - Update KITE_API_KEY and KITE_API_SECRET in .env file');
    }

    if (!config.GOOGLE_CLIENT_ID) {
        console.log('\n💡 Optional: To enable Google OAuth');
        console.log('   - Create a project at https://console.developers.google.com/');
        console.log('   - Enable Google+ API and create OAuth credentials');
        console.log('   - Update GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in .env file');
    }

    rl.close();
}

// Run setup if this file is executed directly
if (require.main === module) {
    setupEnvironment().catch(console.error);
}

module.exports = { setupEnvironment };